export const JUGADORES = [
  {
    id: 0,
    image: "jugador.png",
    title: "",
    description: "BEST OF THE BEST",
    nombre: "Patricio",
    nombreEspalda: "Soriano",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 8,
        cortado: 7,
      },
      reves: {
        plano: 9,
        cortado: 6,
      },
      volea: 5,
      globo: 4,
      remate: 10,
      salidaPared: 6,
    },
    actitud: "positiva",
    pala: "NOX ATTACK",
    winner: "OUH YES!!",
  },
  {
    id: 1,
    ruta: "/jugadores/1",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Carlos",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 8,
        cortado: 7,
      },
      volea: 5,
      globo: 6,
      remate: 9,
      salidaPared: 7,
    },
    actitud: "competitiva",
    pala: "HEAD ALPHA",
    winner: "¡Vamos!",
  },
  {
    id: 2,
    ruta: "/jugadores/2",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Luisa",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 6,
        cortado: 5,
      },
      reves: {
        plano: 8,
        cortado: 4,
      },
      volea: 4,
      globo: 6,
      remate: 8,
      salidaPared: 5,
    },
    actitud: "entusiasta",
    pala: "VARLION LETHAL WEAPON",
    winner: "¡Lo conseguí!",
  },
  {
    id: 3,
    ruta: "/jugadores/3",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Sofía",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 8,
        cortado: 6,
      },
      reves: {
        plano: 7,
        cortado: 5,
      },
      volea: 4,
      globo: 5,
      remate: 9,
      salidaPared: 7,
    },
    actitud: "perseverante",
    pala: "ROYAL PADEL X-FORCE",
    winner: "¡Sí se puede!",
  },
  {
    id: 4,
    ruta: "/jugadores/4",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Miguel",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 6,
        cortado: 4,
      },
      reves: {
        plano: 9,
        cortado: 7,
      },
      volea: 6,
      globo: 5,
      remate: 8,
      salidaPared: 6,
    },
    actitud: "determinado",
    pala: "BABOLAT VIPER CARBON",
    winner: "¡Vamos por más!",
  },
  {
    id: 5,
    ruta: "/jugadores/5",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Ana",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "optimista",
    pala: "ADIDAS CARBON CTRL",
    winner: "¡Lo logramos!",
  },
  {
    id: 6,
    ruta: "/jugadores/6",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Diego",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 8,
        cortado: 6,
      },
      reves: {
        plano: 7,
        cortado: 5,
      },
      volea: 5,
      globo: 6,
      remate: 8,
      salidaPared: 6,
    },
    actitud: "competitiva",
    pala: "WILSON CARBON FORCE",
    winner: "¡A por todas!",
  },
  {
    id: 7,
    ruta: "/jugadores/7",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Elena",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 6,
        cortado: 4,
      },
      reves: {
        plano: 8,
        cortado: 6,
      },
      volea: 4,
      globo: 7,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "resistente",
    pala: "SIUX PLATINUM",
    winner: "¡Nunca te rindas!",
  },
  {
    id: 8,
    ruta: "/jugadores/8",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Mario",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "positiva",
    pala: "VIBORA KING COBRA",
    winner: "¡Soy imparable!",
  },
  {
    id: 9,
    ruta: "/jugadores/9",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Laura",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 6,
        cortado: 4,
      },
      reves: {
        plano: 8,
        cortado: 6,
      },
      volea: 5,
      globo: 7,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "determinada",
    pala: "NOX STINGER",
    winner: "¡Nada me detiene!",
  },
  {
    id: 10,
    ruta: "/jugadores/10",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Javier",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 8,
        cortado: 6,
      },
      reves: {
        plano: 7,
        cortado: 5,
      },
      volea: 5,
      globo: 6,
      remate: 8,
      salidaPared: 6,
    },
    actitud: "comprometido",
    pala: "BULLPADEL HACK",
    winner: "¡Vamos por más!",
  },
  {
    id: 11,
    ruta: "/jugadores/11",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "María",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "optimista",
    pala: "VARLION AVANT",
    winner: "¡Vamos por la victoria!",
  },
  {
    id: 12,
    ruta: "/jugadores/12",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Andrés",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "positiva",
    pala: "DROP SHOT HERITAGE",
    winner: "¡Soy invencible!",
  },
  {
    id: 13,
    ruta: "/jugadores/13",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Paula",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 6,
        cortado: 4,
      },
      reves: {
        plano: 8,
        cortado: 6,
      },
      volea: 5,
      globo: 7,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "determinada",
    pala: "SIUX PEGASUS",
    winner: "¡A por todas!",
  },
  {
    id: 14,
    ruta: "/jugadores/14",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Roberto",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 8,
        cortado: 6,
      },
      reves: {
        plano: 7,
        cortado: 5,
      },
      volea: 5,
      globo: 6,
      remate: 8,
      salidaPared: 6,
    },
    actitud: "competitiva",
    pala: "ADIDAS ADIPOWER",
    winner: "¡Nada me detiene!",
  },
  {
    id: 15,
    ruta: "/jugadores/15",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Isabel",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "positiva",
    pala: "DROP SHOT CONQUEROR",
    winner: "¡Soy invencible!",
  },
  {
    id: 16,
    ruta: "/jugadores/16",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Hugo",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "perseverante",
    pala: "WILSON CARBON FORCE",
    winner: "¡Nada me detiene!",
  },
  {
    id: 17,
    ruta: "/jugadores/17",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Sara",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 6,
        cortado: 4,
      },
      reves: {
        plano: 8,
        cortado: 6,
      },
      volea: 5,
      globo: 7,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "comprometida",
    pala: "NOX ML10 PRO CUP",
    winner: "¡Luchando hasta el final!",
  },
  {
    id: 18,
    ruta: "/jugadores/18",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Alejandro",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 8,
        cortado: 6,
      },
      reves: {
        plano: 7,
        cortado: 5,
      },
      volea: 5,
      globo: 6,
      remate: 8,
      salidaPared: 6,
    },
    actitud: "determinada",
    pala: "HEAD DELTA MOTION",
    winner: "¡Soy imparable!",
  },
  {
    id: 19,
    ruta: "/jugadores/19",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Carmen",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "optimista",
    pala: "VARLION LETHAL WEAPON",
    winner: "¡Vamos por la victoria!",
  },
  {
    id: 20,
    ruta: "/jugadores/20",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Pablo",
    nombreEspalda: "",
    ManoDominante: "Derecha",
    golpes: {
      derecha: {
        plano: 7,
        cortado: 5,
      },
      reves: {
        plano: 6,
        cortado: 4,
      },
      volea: 5,
      globo: 6,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "comprometido",
    pala: "DROP SHOT CONQUEROR",
    winner: "¡Luchando hasta el final!",
  },
  {
    id: 21,
    ruta: "/jugadores/21",
    image: "src/assets/jugador.png",
    title: "",
    description: "",
    nombre: "Lucía",
    nombreEspalda: "",
    ManoDominante: "Izquierda",
    golpes: {
      derecha: {
        plano: 6,
        cortado: 4,
      },
      reves: {
        plano: 8,
        cortado: 6,
      },
      volea: 5,
      globo: 7,
      remate: 7,
      salidaPared: 5,
    },
    actitud: "perseverante",
    pala: "ADIDAS ADIPOWER",
    winner: "¡Nada me detiene!",
  },
];

/*
CREATE TABLE Jugadores (
    id INT PRIMARY KEY,
    nombre VARCHAR(100),
    ManoDominante VARCHAR(20),
    derechaPlano INT,
    derechaCortado INT,
    revesPlano INT,
    revesCortado INT,
    volea INT,
    globo INT,
    remate INT,
    salidaPared INT,
    actitud VARCHAR(50),
    pala VARCHAR(100),
    winner VARCHAR(100)
);

INSERT INTO Jugadores (id, nombre, ManoDominante, derechaPlano, derechaCortado, revesPlano, revesCortado, volea, globo, remate, salidaPared, actitud, pala, winner) 
VALUES
(0, 'Jeni', 'Derecha', 8, 7, 9, 6, 5, 4, 10, 6, 'positiva', 'NOX ATTACK', 'OUH YES!!'),
(1, 'Carlos', 'Izquierda', 7, 5, 8, 7, 5, 6, 9, 7, 'competitiva', 'HEAD ALPHA', '¡Vamos!'),
(2, 'Luisa', 'Derecha', 6, 5, 8, 4, 4, 6, 8, 5, 'entusiasta', 'VARLION LETHAL WEAPON', '¡Lo conseguí!'),
(3, 'Sofía', 'Derecha', 8, 6, 7, 5, 4, 5, 9, 7, 'perseverante', 'ROYAL PADEL X-FORCE', '¡Sí se puede!'),
(4, 'Miguel', 'Izquierda', 6, 4, 9, 7, 6, 5, 8, 6, 'determinado', 'BABOLAT VIPER CARBON', '¡Vamos por más!'),
(5, 'Ana', 'Derecha', 7, 5, 6, 4, 5, 6, 7, 5, 'optimista', 'ADIDAS CARBON CTRL', '¡Lo logramos!'),
(6, 'Diego', 'Izquierda', 8, 6, 7, 5, 5, 6, 8, 6, 'competitiva', 'WILSON CARBON FORCE', '¡A por todas!'),
(7, 'Elena', 'Derecha', 6, 4, 8, 6, 4, 7, 7, 5, 'resistente', 'SIUX PLATINUM', '¡Nunca te rindas!'),
(8, 'Mario', 'Derecha', 7, 5, 6, 4, 5, 6, 7, 5, 'positiva', 'VIBORA KING COBRA', '¡Soy imparable!'),
(9, 'Laura', 'Izquierda', 6, 4, 8, 6, 5, 7, 7, 5, 'determinada', 'NOX STINGER', '¡Nada me detiene!'),
(10, 'Javier', 'Derecha', 8, 6, 7, 5, 5, 6, 8, 6, 'comprometido', 'BULLPADEL HACK', '¡Vamos por más!'),
(11, 'María', 'Izquierda', 7, 5, 6, 4, 5, 6, 7, 5, 'optimista', 'VARLION AVANT', '¡Vamos por la victoria!'),
(12, 'Andrés', 'Derecha', 7, 5, 6, 4, 5, 6, 7, 5, 'positiva', 'DROP SHOT HERITAGE', '¡Soy invencible!'),
(13, 'Paula', 'Izquierda', 6, 4, 8, 6, 5, 7, 7, 5, 'determinada', 'SIUX PEGASUS', '¡A por todas!'),
(14, 'Roberto', 'Derecha', 8, 6, 7, 5, 5, 6, 8, 6, 'competitiva', 'ADIDAS ADIPOWER', '¡Nada me detiene!'),
(15, 'Isabel', 'Izquierda', 7, 5, 6, 4, 5, 6, 7, 5, 'positiva', 'DROP SHOT CONQUEROR', '¡Soy invencible!'),
(16, 'Hugo', 'Derecha', 7, 5, 6, 4, 5, 6, 7, 5, 'perseverante', 'WILSON CARBON FORCE', '¡Nada me detiene!'),
(17, 'Sara', 'Izquierda', 6, 4, 8, 6, 5, 7, 7, 5, 'comprometida', 'NOX ML10 PRO CUP', '¡Luchando hasta el final!'),
(18, 'Alejandro', 'Derecha', 8, 6, 7, 5, 5, 6, 8, 6, 'determinada', 'HEAD DELTA MOTION', '¡Soy imparable!'),
(19, 'Carmen', 'Izquierda', 7, 5, 6, 4, 5, 6, 7, 5, 'optimista', 'VARLION LETHAL WEAPON', '¡Vamos por la victoria!'),
(20, 'Pablo', 'Derecha', 7, 5, 6, 4, 5, 6, 7, 5, 'comprometido', 'DROP SHOT CONQUEROR', '¡Luchando hasta el final!'),
(21, 'Lucía', 'Izquierda', 6, 4, 8, 6, 5, 7, 7, 5, 'perseverante', 'ADIDAS ADIPOWER', '¡Nada me detiene!');
*/
